// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY9ywuIsw83XX5KVzzRm0F9PA4lHq1lMY',
    appId: '1:461621943340:web:8cf9be47f39828e0804589',
    messagingSenderId: '461621943340',
    projectId: 'flutterfirebaseinfraviewpro',
    authDomain: 'flutterfirebaseinfraviewpro.firebaseapp.com',
    storageBucket: 'flutterfirebaseinfraviewpro.firebasestorage.app',
    measurementId: 'G-GBJYS1XFDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWMAVtOXEj1gpc82Qc_tKCI8L3eznAh0I',
    appId: '1:461621943340:android:77eb673363d65ee2804589',
    messagingSenderId: '461621943340',
    projectId: 'flutterfirebaseinfraviewpro',
    storageBucket: 'flutterfirebaseinfraviewpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBxbDCzIEiSQxVHVAnRwAxM_FjX-QKE5s',
    appId: '1:461621943340:ios:6137acb1841fda66804589',
    messagingSenderId: '461621943340',
    projectId: 'flutterfirebaseinfraviewpro',
    storageBucket: 'flutterfirebaseinfraviewpro.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseInfraviewPro2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBxbDCzIEiSQxVHVAnRwAxM_FjX-QKE5s',
    appId: '1:461621943340:ios:6137acb1841fda66804589',
    messagingSenderId: '461621943340',
    projectId: 'flutterfirebaseinfraviewpro',
    storageBucket: 'flutterfirebaseinfraviewpro.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseInfraviewPro2',
  );
}
